name: Deploy

on:
  repository_dispatch:
    types:
      - commit-to-branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Print Branch Information
        run: |
          echo "===== Initiated deploy: ${{ github.event.client_payload.owner }} \n \
               repo   :${{ github.event.client_payload.repo }} \n \
               branch :${{ github.event.client_payload.branch }} \n \
               sha    :${{ github.event.client_payload.sha }}\n"