name: Deploy

on:
  repository_dispatch:
    types:
      - commit-to-branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Print Branch Information
        run: |
          echo "===== Initiated deploy ${{ github.event.client_payload.owner }} ===== "
          echo " repo   : ${{ github.event.client_payload.repo }}"
          echo " branch : ${{ github.event.client_payload.branch }} "
          echo " sha    : ${{ github.event.client_payload.sha }}"
          echo "=================================================================3===== "