name: Deploy

on:
  repository_dispatch:
    types:
      - commit-to-branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Print Branch Information
        run: |
          echo "owner: ${{ github.event.client_payload.owner }}  \
               repo:${{ github.event.client_payload.repo }} \
               branch:${{ github.event.client_payload.branch }} \
               sha:${{ github.event.client_payload.sha }}"